(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
operatorsWL::usage="Matrix operators: opY, opF with fL2[\[Psi],\[Sigma]], fL1[\[Psi],\[Sigma]] and replacement rules: ARule, explicitARule, potentialRule. Note that the operators have the flat measure for the scalar product.";

opY=({
 {(m-\[Lambda]+V[\[Sigma]])#&, (-fL1[#,\[Sigma]])&},
 {(-fL2[#,\[Sigma]])&, (m+\[Lambda])#&}
});
opF=({
 {(m+\[Lambda])#&, fL1[#,\[Sigma]]&},
 {fL2[#,\[Sigma]]&, (m-\[Lambda]+V[\[Sigma]])#&}
});

fL1[\[Psi]_,\[Sigma]_]:=A[\[Sigma]] Sqrt[\[Sigma]^2-1] \!\(
\*SubscriptBox[\(\[PartialD]\), \(\[Sigma]\)]\[Psi]\)+((1+2 \[Sigma]^2) A[\[Sigma]])/(2 \[Sigma] Sqrt[-1+\[Sigma]^2]) \[Psi]

fL2[\[Psi]_,\[Sigma]_]:=A[\[Sigma]] Sqrt[\[Sigma]^2-1] \!\(
\*SubscriptBox[\(\[PartialD]\), \(\[Sigma]\)]\[Psi]\)+(-4 \[Sigma]+(-1+4 \[Sigma]^2) A[\[Sigma]]) /(2 \[Sigma] Sqrt[-1+\[Sigma]^2]) \[Psi]

ARule={A'[c_]->(2 (-1+c A[c]))/(-1+c^2),A''[c_]->(2 A[c])/(-1+c^2),A'''[c_]->-(4/(-1+c^2)^2),A''''[c_]->(16 c)/(-1+c^2)^3};
explicitARule={A->Function[c,c+1/2 (c^2-1) Log[(c-1)/(c+1)]]};
potentialRule={m->1, V->Function[\[Sigma],A[\[Sigma]]/\[Sigma]]};



